import './globals.sass'
import Header from '@components/Header/Header'
import Footer from '@components/Footer/Footer'
import { Roboto } from '@next/font/google'
import Provider from '@/Utils/Redux/Provider'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  style: ['normal'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div id='modal'></div>
        <Provider>
          <Header />
          <main>
            {children}
          </main>
          <Footer />
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout